package com.gguoliang.generic;

/**
 * @Author GGuoLiang
 * @Date 2021/1/2 10:14 下午
 * @Version 1.0
 */
public class MyNode extends Node<Integer> {

    private Integer data;

    @Override
    public Integer getData() {
        return data;
    }


    /**
     * // Bridge method generated by the compiler
     * // 编译器产生的桥接方法
     * public void setData(Object data) {
     *         setData((Integer) data);
     * }
     * @param data
     */
    @Override
    public void setData(Integer data) {
        this.data = data;
    }

    public MyNode(Integer data) {
        this.data = data;
    }
}
